name: Test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  checks:
    name: Check PHP 8.2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --prefer-dist --ignore-platform-reqs --no-interaction

      - name: Check code styling
        run: composer ecs-check

      - name: Create keys
        run: sh ./bin/create_keys

      - name: Run unit and feature tests
        run: composer test
